### PR TITLE
feat:Better api for EventTimer

### PR DESCRIPTION
**Pull request by ashishpuliyel**
## What does this change?
Adds a EventTimer.get() method 

## Why?
Easier to access the singleton.

### CODE REVIEW

**Review by ioanna0 — APPROVED** [review]
looks good 👍

**Comment by mxdvl** [comment]
Maybe we could also make use of the [`log('commercial', event)`][1] to log commercial-specific info?

[1]: https://github.com/guardian/libs/blob/main/src/logger.README.md

**Comment by ioanna0** [comment]
I didn't trigger a release for some reason 🤔 should we push an empty one in main?

**Comment by mxdvl** [comment]
Coverage decreased, meaning the build was unsuccessful, meaning it did not release.

Same as #138. 😢

**Pull request merged**
