### PR TITLE
feat!: Remove Lotame

### PR DESCRIPTION
**Pull request by mxdvl**
⚠️ Do not merge before Jan 14th, 2021 ⚠️

## What does this change?

Removes Lotame as a vendor.

## Why?

Lotame was used as part of Ozone, but this is no longer the case. See [Trello card](https://trello.com/c/64ae583b/1241-remove-lotame-ozone-on-the-14th-jan-2021).

### CODE REVIEW

**Review by ioanna0 — APPROVED** [review]
Bye Lotame! 🧹

**Comment by mxdvl** [comment]
⚠️ Do not merge before Jan 14th ⚠️

**Comment by mxdvl** [comment]
This should actually have triggered a major release, as it’s a breaking change for anyone depending on Lotame…

**Comment by sndrs** [comment]
i think the build was not successful, so no publish https://github.com/guardian/commercial-core/commit/686ecefc024965c866c79340b54b066e499d06e9

**Comment by mxdvl** [comment]
And only because coverage went down…
Note to self: check the build is successful and package is _actually_ published.

**Pull request merged**
