### PR TITLE
fix: Export LotameData type

### PR DESCRIPTION
**Pull request by ioanna0**
continuing from https://github.com/guardian/commercial-core/pull/56 adding the export line in index.ts

### CODE REVIEW

**Review by sndrs — APPROVED** [review]

**Comment by ioanna0** [comment]
@sndrs for some reason this PR didn't trigger a semantic release 🤷🏻‍♀️🤷🏻‍♀️
I tried to re-run the CI steps and i've made it worse, it now fails on  Docs step 🥺

**Comment by mxdvl** [comment]
I think you didn’t “squash and merge”… Looking at [the commit history][main], I can see your ad89dcf commit as-is.

[main]: https://github.com/guardian/commercial-core/commits/main

**Comment by ioanna0** [comment]
> I think you didn’t “squash and merge”… Looking at [the commit history](https://github.com/guardian/commercial-core/commits/main), I can see your [ad89dcf](https://github.com/guardian/commercial-core/commit/ad89dcff89fc9a6dbabf4951469cfd2fbebf098d) commit as-is.

Strange, yes the commit looks as-is indeed. Although i'm sure I clicked `Squash and Merge` that's the button available now

**Comment by mxdvl** [comment]
Could this be because there’s only one (1) commit, excluding merges?

**Comment by ioanna0** [comment]
Could be 🤷🏻‍♀️

@sndrs 
What's the best way to manually trigger a release in this case? I though few ways
1. amend the last commit in main - probably not a good idea to directtly manipulate the main branch
2. trigger a release in main via np? - tried this but it's not available 
3. revert and re-revert to put it back

**Pull request merged**
