### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by mxdvl**
## What does this change?

Update dependencies.

## Why?

Make @dependabot happy:

- #77
- #76
- #75
- #73

### CODE REVIEW

**Comment by mxdvl** [comment]
It looks like we have clashing definitions between Prettier and ESLint when it comes to semicolons in type declarations.

Prettier wants them gone, ESLint needs them all…

**Comment by sndrs** [comment]
> It looks like we have clashing definitions between Prettier and ESLint when it comes to semicolons in type declarations.

ooooh intersting, i'll look at the config

**Comment by mxdvl** [comment]
Config fixed in https://github.com/guardian/configs/pull/5

**Comment by mxdvl** [comment]
Here are the supported PR titles, as per the error logs:

```markdown
> Error: Unknown release type "deps" found in pull request title "deps: update". 

Available types:
 - feat: A new feature
 - fix: A bug fix
 - improvement: An improvement to a current feature
 - docs: Documentation only changes
 - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
 - refactor: A code change that neither fixes a bug nor adds a feature
 - perf: A code change that improves performance
 - test: Adding missing tests or correcting existing tests
 - build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
 - ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
 - chore: Other changes that don't modify src or test files
 - revert: Reverts a previous commit
```

**Review by sndrs — APPROVED** [review]

**Pull request merged**
